version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbpt-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dspace:dspace@db:5432/chatbpt
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=HS256
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:14
    container_name: chatbpt-db
    environment:
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
      POSTGRES_DB: chatbpt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: